README.md
lib/measured-rails.rb
lib/measured/rails/active_record.rb
lib/measured/rails/base.rb
lib/measured/rails/units/length.rb
lib/measured/rails/units/weight.rb
lib/measured/rails/validations.rb
measured-rails.gemspec
test/active_record_test.rb
test/dummy/app/models/thing.rb
test/dummy/app/models/validated_thing.rb
test/dummy/db/migrate/20150419151735_create_things.rb
test/dummy/db/migrate/20150419155505_create_validated_things.rb
test/dummy/db/schema.rb
test/test_helper.rb
test/validation_test.rb

@Shopify/shipping @qq99 @patrickdonovan 
This implements the Rails/ActiveRecord adapter for the [measured](https://github.com/Shopify/measured) measurement gem.
It provides a mapping from the measurement to a `_value` and `_unit` column in the DB. It manages retrieval and storage, bulk updating, validations, and exception handling.
The best way to understand what this gem does is to read the new README:
https://github.com/Shopify/measured-rails/blob/initial-implementation/README.md
The diff looks big, but it's actually only a little over a hundred lines of feature code. The rest is tests, README, and gem scaffolding.

Rails adapter initial implementation

---

README.md
lib/measured/rails/validations.rb
lib/measured/rails/version.rb
measured-rails.gemspec
test/dummy/app/models/validated_thing.rb
test/dummy/db/migrate/20150512214352_add_numericality.rb
test/dummy/db/schema.rb
test/validation_test.rb

@Shopify/shipping 
Adds numericality validations on the ```measured``` fields to support numerical comparisons like ```<, ==, >, <=, >=``` as you'd expect. We can now validate ```measured``` fields in the model to be within certain pre-set bounds. Differences in units while doing bound validation checks also works. You can also set custom validation error messages for failing validations. 
For example, you can set a ```measured``` field called ```length``` in your model and create validations for it like, 
```ruby
measured_length :length
validates :length, measured: {greater_than: Measured::Length.new(3, :m), less_than: Measured::Length.new(500, :cm), message: "Custom validation error message"}
```
Validating against non-Measured fields raises an error. You can also pass ```Proc```s while …

Add numericality validator options to measured

---

README.md
lib/measured/rails/validations.rb
lib/measured/rails/version.rb
measured-rails.gemspec
test/dummy/app/models/validated_thing.rb
test/dummy/db/migrate/20150512214352_add_numericality.rb
test/dummy/db/schema.rb
test/validation_test.rb

**Context**
Continuation of https://github.com/Shopify/measured/pull/12
Numericality validations are great for rails models. Moreover, it is likely that a lot of validations will be some sort of comparison against a zero valued ```Measured::Measurable``` object. Changes proposed in this PR make that particular case easy, since comparison against zero is a very natural thing to do and expecting to pass in the units of the zero value makes no sense.  i.e we should be able to compare against ```0``` and shouldn't have to specify the units, like ```Measured::Length(0, :cm)```
**Example**
```ruby
class AntiMatter < ActiveRecord::Base
measured_weight :negative_weight
validates :negative_weight, measured: {less_than: 0} ## as opposed to Measured::Weight(0, :kg)
end
```
Attempting numericalty …

Scalar validator

---

lib/measured/rails/active_record.rb
test/active_record_test.rb

Round to column precision when recording the to the `field_value`.
cc @kmcphillips @cyprusad

Round to column precision

---

lib/measured/rails/active_record.rb
lib/measured/rails/version.rb
test/active_record_test.rb

So instead of rounding the number to the correct number of overall significant digits (i.e the column's precision) we are now rounding to the allowed scale (i.e permitted number of digits after the decimal point for a coumn)
This still leaves a bug where a number has total digits > column's precision as well as # of digits after decimal point > column's scale. Investigating how to get around this case.
For review @garethson @kmcphillips

Rounding the decimal value to the column's permitted rounding scale

---

lib/measured/rails/active_record.rb
test/active_record_test.rb

@garethson @kmcphillips 
Round the number and only then raise if there are more significant digits than the column can handle.

Round numbers before raising errors about numbers having large # of significant digits

---

lib/measured/rails/validations.rb
test/dummy/app/models/validated_thing.rb
test/dummy/db/migrate/20152911214351_add_scalar_numericality_comparison.rb
test/dummy/db/schema.rb
test/validation_test.rb

We currently don't support this in Shopify:
```ruby
validates :length, :width, :height, measured: {greater_than: 0, less_than: 999999}
```
which causes us to have to change it to
```ruby
validates :length_value, :width_value, :height_value, numericality: {greater_than: 0, less_than: 999999, allow_nil: true}
```
which is unfortunate, as we loose our nice error messages and also expose the internals of `Measured` to the consuming interface.
I realize that enforcing a `less_than: X` on a Measurable field can seem strange, but in reality most of our use cases currently need to do this. The limits that software puts on fields is *usually* because of underlying storage constraints, not some real-world limit, like "over 100 lbs". This gives us the ability to still do both.
@cyprusad @kmcphillips …

Allow numeric comparison against scalar.

---

lib/measured/rails/active_record.rb
test/active_record_test.rb

Our validation for column size had a small bug in that the check for precision could fail:
```
[1] pry(#<Thing>)> BigDecimal.new('2000000000000').split
=> [1, "2", 10, 13]
```
We then to "2".length which was < `precision` and our check failed us.
@trishume @kmcphillips

Fix check for BigDecimal precision

---

lib/measured/rails/active_record.rb
lib/measured/rails/version.rb
test/active_record_test.rb
test/dummy/app/models/thing.rb
test/dummy/db/migrate/20150419151735_create_things.rb
test/dummy/db/schema.rb

Give the option of limiting the value on assignment to our measured fields. Since we enforce the database field size on assignment anyway, providing the option to always limit the value will remove a lot of code in the consuming Shopify code base that has to default these values to the max size the field can handle.
@kmcphillips @cyprusad @trishume

Adds max_on_assignment option.

---

lib/measured/rails/version.rb
measured-rails.gemspec

@garethson 
Replaces #17. Bumps version to 1.1.0 to stay in line with https://github.com/Shopify/measured which is at the same version. Keep them in parallel to make versioning simple.

Bump version to 1.1.0

---

test/active_record_test.rb

@garethson @RichardBlair 
I'm chasing a `Measured::UnitError·Unit X does not exist` error. I thought it might be in measured (it's not) but I was not confident in our test coverage around this.
No functional changes. Just test improvements.

Improve tests around invalid units and saving

---

lib/measured/rails/validations.rb
test/active_record_test.rb

@cyprusad @garethson @RichardBlair @mdking 
Found the bug. Follow up to #20.
If the unit is already known to be invalid, but there is a validation that _includes_ a numericality check we try to instantiate the measurement to do comparisons. But then that would raise.
So just skip the numericality checks if the unit is already known to be invalid. Can't do anything about it anyway.

Do not error if unit is already known to be invalid

---

lib/measured/rails/validations.rb
test/validation_test.rb

@cyprusad @garethson @RichardBlair
Another follow up bug fix for #21.
Don't do numericality checks if the value is `nil`. Happens when someone sends malformed request and basically does:
```ruby
thing.weight_value = nil
thing.weight_unit = :g
```
The unit is valid but then tries to compare the value of `nil` against the value in the validation.
Exception looks something like:
```
NoMethodError:         NoMethodError: undefined method `>' for nil:NilClass
(measured-rails-1.3.1) lib/measured/rails/validations.rb:32 in `public_send`
(measured-rails-1.3.1) lib/measured/rails/validations.rb:32 in `block in validate_each`
```

Do not compare if the value is nil

---

.travis.yml
Gemfile
gemfiles/rails-4.2.gemfile
gemfiles/rails-5.0.gemfile

@benwah @jonathankwok 
Make mainline rails 5 the default build. Test with 4.2 as legacy.
Aligns with https://github.com/Shopify/measured/pull/27

Test with consistent Ruby/Rails versions

---

lib/measured/rails/validations.rb
test/validation_test.rb

**Problems**
- We were validating presence wrong: when receiving multiple dimensions to validate at once, we were validating the first, and then quitting.
- Models using `measured` also validate presence via Rails, meaning the same validation is happening twice. This leads to duplicate errors when a validation fails.
**Solution**
Instead of fixing, we're removing validation logic from the gem, relying on Rails to validating presence. This will also resolve our duplicate error issues.
**Review**
Basically just deleted a bunch of code (and changed a test to now allow nil value since our models will be responsible for validating that).

Stop validating presence

---

measured-rails.gemspec

@benwah @jonathankwok 
We keep `measured` and `measured-rails` at the same version. Even if it means releasing empty versions to keep them in sync. Much clearer way to understand how the versions interact and their dependencies.
Make this explicit in the gemspec. Don't let the release person forget to update the dependency.

Explicitly lock to measured version

---

README.md
lib/measured/rails/active_record.rb
lib/measured/rails/validations.rb
test/active_record_test.rb
test/dummy/app/models/thing_with_custom_unit_accessor.rb
test/dummy/db/migrate/20152911214351_add_scalar_numericality_comparison.rb
test/dummy/db/migrate/20161118203701_create_thing_with_custom_unit_accessors.rb
test/dummy/db/schema.rb
test/validation_test.rb

**Problem**
With the current implementation of measured-rails, we need a separate column to hold the units of each declared field. Sometimes you might want to just use the same column to hold these units, but this is not possible.
**Solution**
I'm suggesting that we add an option when declaring `measured_length` and `measured_weight`: `unit_column_name`. This tells measured-rails which field it should read the unit from.
**Sample usage**
```ruby
class ThingWithCustomUnitAccessor < ActiveRecord::Base
measured_length :length, :width, :height,      unit_column_name: :size_unit
measured_weight :total_weight, :extra_weight, unit_column_name: :weight_unit
end
```
CR: @kmcphillips @MalazAlamir

Add support for customizing the column holding the measured unit

---

measured-rails.gemspec

@benwah @thegedge 
Closes #30
We only run tests on Rails 4.2 and up, and those are the only currently supported versions of Rails.
Related to https://github.com/Shopify/measured/pull/43

Explicitly support 4.2 and up only

---

.travis.yml
gemfiles/rails-master.gemfile
test/active_record_test.rb

@benwah @thegedge @sgrif 
https://twitter.com/sgrif/status/804037955241312258
Run against rails master in CI.

Run CI against rails master

---

.travis.yml
gemfiles/rails-5.0.gemfile

Include Ruby 2.4.0 in our CI list. Skip Rails 4.2 as there is a JSON version conflict.
Related to https://github.com/Shopify/measured/pull/56

Test with ruby 2.4.0

---

measured-rails.gemspec
test/test_helper.rb

Adds `minitest-reporters` and unsticks us from old test versions.
Related to https://github.com/Shopify/measured/pull/82

Add minitest reporters and update gems

---

README.md
lib/measured/rails/active_record.rb
lib/measured/rails/validations.rb
lib/measured/rails/version.rb
test/active_record_test.rb
test/dummy/app/models/validated_thing.rb
test/dummy/db/migrate/20170201223955_remove_scalar_fields.rb
test/validation_test.rb

Bringing `measured-rails` in line with the prerelease of `measured`, which focused on correctness and performance.
The two biggest changes here would be:
1. the removal of scalars for comparisons, and
2. return `Measured::Unit` instances for `Measurable#unit`, which requires us to generally call `Unit#name` to get the same result (since `Measurable#unit` was the unit name previously).

Bump version to 2.0.0.pre4

---

test/dummy/config/application.rb

When we run `bundle exec rake test` we run into the following problem:
```
➜  measured-rails git:(master) bundle exec rake test
/opt/rubies/2.3.1/bin/ruby -w -I"lib:test:lib/**/*" -I"/Users/lucasuyezu/.gem/ruby/2.3.1/gems/rake-12.0.0/lib" "/Users/lucasuyezu/.gem/ruby/2.3.1/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/active_record_test.rb" "test/validation_test.rb"
/Users/lucasuyezu/.gem/ruby/2.3.1/gems/activerecord-5.1.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `raise_in_transactional_callbacks=' for ActiveRecord::Base:Class (NoMethodError)
from /Users/lucasuyezu/.gem/ruby/2.3.1/gems/activerecord-5.1.3/lib/active_record/railtie.rb:112:in `block (3 levels) in <class:Railtie>'
from /Users/lucasuyezu/.gem/ruby/2.3.1/gems/activerecord-5.1.3/lib/ac …
```

Remove deprecated option

---

lib/measured/rails/validations.rb
test/active_record_test.rb
test/dummy/app/models/validated_thing.rb
test/dummy/db/schema.rb
test/validation_test.rb

This PR lets one pass a lambda or proc to the `message` option when adding a new validation. This gives more control in cases where one might need the invalid data to be part of the error message.
```ruby
class ValidatedThing < ActiveRecord::Base
measured_length :weight
validates :weight,
measured: {
greater_than_or_equal_to: Measured::Weight.new(0, :g),
message: Proc.new { |record| "#{record.length_message_from_block_unit} is not a valid unit" }
}
end
```
cc @mdking @MalazAlamir

Make the message validation option accept a block

---

lib/measured/rails/validations.rb
test/validation_test.rb

This fixes a silly duplicate error message where if you try to assign a unit that is not supported by the gem at all, the validation message will show twice. 
Before:
```
[1] pry(#<Measured::Rails::ValidationTest>)> thing.length_units_singular_unit = :t
=> :t
[2] pry(#<Measured::Rails::ValidationTest>)> thing.valid?
=> false
[3] pry(#<Measured::Rails::ValidationTest>)> thing.errors.full_messages
=> ["Length units singular custom message too", "Length units singular custom message too"]
```
After:
```
[1] pry(#<Measured::Rails::ValidationTest>)> thing.length_units_singular_unit = :t
=> :t
[2] pry(#<Measured::Rails::ValidationTest>)> thing.valid?
=> false
[3] pry(#<Measured::Rails::ValidationTest>)> thing.errors.full_messages
=> ["Length units singular custom message too"]
```

Fix duplicate error message for non-supported units

---

lib/measured/rails/version.rb

Release version 2.1.0.
- [measured](https://github.com/Shopify/measured/compare/v2.0.0...v2.1.0).
- [measured-rails](https://github.com/Shopify/measured-rails/compare/ac7a049745c3cf170f84faa2fb174a7d6c7134cf...release_version_2_1_0).
measured's version on [gemspec](https://github.com/Shopify/measured-rails/blob/0c53f63368de3dff56748def5b14e3b131d758f1/measured-rails.gemspec#L21-L21) is pointing to `Measured::Rails::VERSION`, so updating it here will do the trick.
cc @mdking @MalazAlamir

Bump version to 2.1.0

---

lib/measured/rails/version.rb

Bump version to `2.2.0` to use that [`measured` version](https://github.com/Shopify/measured/commit/3139d0fd25299ec46a25edd340f6a5e12d18bae3)

Bump version

---

lib/measured/rails/version.rb

Bump `measured-rails` to `'2.3.0'` to match [`measured` latest version](https://github.com/Shopify/measured/pull/100).
The only change in this package has been some key removal from our `dev.yml`: https://github.com/Shopify/measured-rails/compare/v2.2.0...be4ae0b

Update version to 2.3.0 to match measured

---

lib/measured/rails/active_record.rb

In some cases, where we are overriding the names of the properties used, we will read an ivar that does not yet exist.
It will return `nil` but ruby will spit out a warning.
Here we guard against that and just have it return `nil` without reading if it is not defined. Removes these warnings:
```
/measured-rails/lib/measured/rails/active_record.rb:37: warning: instance variable @measured_length not initialized
/measured-rails/lib/measured/rails/active_record.rb:37: warning: instance variable @measured_total_weight not initialized
/measured-rails/lib/measured/rails/active_record.rb:37: warning: instance variable @measured_width not initialized
/measured-rails/lib/measured/rails/active_record.rb:37: warning: instance variable @measured_width not initialized …
```

Do not read an instance variable if it is not defined.

---

test/test_helper.rb

Our test output is a mess in this gem. Large part is that there are two reporters formatting the output and writing double.
Details in here, but mostly we can just work around it by forcing the rails minitest extension to unload: https://github.com/kern/minitest-reporters/issues/230 https://github.com/rails/rails/issues/30491
```
/home/kevin/.rbenv/versions/2.3.1/bin/ruby -w -I"lib:test:lib/**/*" -I"/home/kevin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib" "/home/kevin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/active_record_test.rb" "test/validation_test.rb" 
-- create_table("thing_with_custom_unit_accessors", {:force=>:cascade})
-> 0.0031s
-- create_table("things", {:force=>:cascade})
-> 0.0006s
-- …
```

Work around bug in rails test formatter and Minitest

---

.travis.yml
gemfiles/rails-5.1.gemfile

This modernizes the requirements for ruby and rails for this gem. ruby >= 2.3 and rails >= 5.0.
Also adds ruby 2.6.
It matches the maintenance policies of both:
https://guides.rubyonrails.org/maintenance_policy.html
https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/
Will follow up with a version change.
Matched with https://github.com/Shopify/measured/pull/120

Raise ruby requirement to 2.3 and rails to 5.0

---

lib/measured/rails/active_record.rb

In trying to remove warnings I hit these:
```
measured/rails/active_record.rb:78: warning: method redefined; discarding old size_unit=
measured/rails/active_record.rb:78: warning: previous definition of size_unit= was here
measured/rails/active_record.rb:78: warning: method redefined; discarding old size_unit=
measured/rails/active_record.rb:78: warning: previous definition of size_unit= was here
measured/rails/active_record.rb:78: warning: method redefined; discarding old weight_unit=
measured/rails/active_record.rb:78: warning: previous definition of weight_unit= was here
```
Which is `define_method("#{ unit_field_name }=")` triggering multiple times on redefinition of a field.
This was added in #27
There are a few things. First, the `defined_unit_accessors` never actually worked as …

Fix warnings by using `method_defined?` or `redefine_method`

---

lib/measured-rails.rb
lib/measured/rails/active_record.rb
lib/measured/rails/base.rb
lib/measured/rails/railtie.rb
lib/measured/rails/units/length.rb
lib/measured/rails/units/volume.rb
lib/measured/rails/units/weight.rb
lib/measured/rails/validations.rb
lib/measured/rails/version.rb
test/active_record_test.rb
test/support/models/thing.rb
test/support/models/thing_with_custom_unit_accessor.rb
test/support/models/validated_thing.rb
test/test_helper.rb
test/validation_test.rb

Adds the `# frozen_string_literal: true` comment everywhere.
Related to https://github.com/Shopify/measured/pull/123

Add # frozen_string_literal: true

---

.travis.yml

Mirrors https://github.com/Shopify/measured/pull/130
Supports just the mainline current ruby versions. https://www.ruby-lang.org/en/downloads/

Fix ruby versions and gem install for Travis

---

measured-rails.gemspec
test/test_helper.rb

Mirrors https://github.com/Shopify/measured/pull/131
Fixes a small deprecation in Mocha:
```
Mocha deprecation warning at /Users/kevin/source/measured/test/test_helper.rb:6:in `require': Require 'mocha/test_unit', 'mocha/minitest' or 'mocha/api' instead of 'mocha/setup'.
```
Set minimum version of Mocha where this file is supported to `1.4.0`:
https://github.com/freerange/mocha/blob/master/RELEASE.md#140

Update minitest loader for mocha to remove deprecation

---

CHANGELOG.md
lib/measured/rails/version.rb

A release to include https://github.com/Shopify/measured-rails/pull/67
It bumps dev ruby and drops support for ruby 2.5. I also renamed `master` to `main`.
Full diff: https://github.com/Shopify/measured-rails/compare/31bd920c55e915dd111726fb1461892a1308cfe9...9abdb5487348611beadd563c075171e215b1286f
https://github.com/Shopify/measured/pull/139 was already shipped to `2.8.0` as well.

Release 2.8.0

---

lib/measured/rails/validations.rb
test/validation_test.rb

This just copies the functionality already available for custom
unit accessors. Seems like just an oversight that it wasn't
included for value accessors

Allow custom value accessors with validations

---

CHANGELOG.md
lib/tapioca/dsl/compilers/measured_rails.rb
measured-rails.gemspec
test/tapioca/dsl/compilers/measured_rails_test.rb
test/test_helper.rb

It is difficult to add typing information to sytems when models utilize `measured_rails` currently because there's no typing for the generated methods. This PR adds a tapioca compiler to do this. Historically, these seem to be put into tapioca itself, but [this snippet](https://github.com/Shopify/tapioca/blob/95d76a41fafa3466e2149a1a6b81015c5a669be5/lib/tapioca/loaders/dsl.rb#L53-L55) frees us up to put these compilers directly into the gems that implement a DSL.
I had originally written this to go into tapioca itself, but had someone recommend that I add it here.
Currently CI is failing for ruby 2.6 which has reached its end of life. Relies on #72 to be mergable.

Add Tapioca::Dsl::Compilers::MeasuredRails

---

.github/workflows/ci.yml
lib/tapioca/dsl/compilers/measured_rails.rb
test/tapioca/dsl/compilers/measured_rails_test.rb

Now that Tapioca has adopted the pattern of not defining the DSL compiler if the target class for the DSL is not defined at all, we should be using it in this gem's DSL compiler as well.
I also had to exclude Rails edge + Ruby 3.0 from the build matrix so that the CI can be green.

Small DSL compiler refactor
